### ISSUE TITLE
Create a meta .github repo for the Silverstripe organisation

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#1]
Currently each repository has its own meta files such as "CONTRIBUTING", "SECURITY" etc which are (or should be) identical - or those may be missing entirely. There's no standard or any process for updating them. Ideally those should be standard and all point to the relevant docs.

- A `.github` repository allows us to have [default meta files](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file).
- It also allows us to have a README.md file at the organisation level (see [Laravel's repo](https://github.com/laravel/) as an example) which will display on https://github.com/silverstripe. We can use this to give a general overview of Silverstripe CMS, how to get started, how to contribute, etc.
- Finally, it can be used as a centralised space for conversations that don't really apply to any given repository. Historically those discussions have been held in the silverstripe/silverstripe-framework repository.

## Acceptance Criteria
- [x] A new `.github` repository exists
- [x] An organisation-level README.md file exists with some helpful information
- [x] Appropriate default meta files have been created
- [ ] The existing meta files in individual repos are removed, so that the default files can apply
- [x] Validate that we are using the BSD-3 on all repos except docs.
- [x] Only applies to the Silverstripe organisation NOT symbiote, bringyourownideas, etc

## PRs
- https://github.com/silverstripe/.github/pull/67
- https://github.com/silverstripe/api.silverstripe.org/pull/111
- https://github.com/silverstripe/demo.silverstripe.org/pull/64
- https://github.com/silverstripe/doc.silverstripe.org/pull/268
- https://github.com/silverstripe/gha-auto-tag/pull/5
- https://github.com/silverstripe/gha-ci/pull/70
- https://github.com/silverstripe/gha-generate-matrix/pull/58
- https://github.com/silverstripe/gha-issue/pull/2
- https://github.com/silverstripe/gha-keepalive/pull/6
- https://github.com/silverstripe/gha-pull-request/pull/4
- https://github.com/silverstripe/gha-run-tests/pull/13
- https://github.com/silverstripe/gha-tag-release/pull/10
- https://github.com/silverstripe/gha-update-js/pull/14
- https://github.com/silverstripe/github-issue-search-client/pull/110
- https://github.com/silverstripe/gha-dispatch-ci/pull/2
- https://github.com/silverstripe/silverstripe-config/pull/88
- https://github.com/silverstripe/silverstripe-dms-cart/pull/48
- https://github.com/silverstripe/silverstripe-frameworktest/pull/142
- https://github.com/silverstripe/silverstripe-lessons-v4/pull/117
- https://github.com/silverstripe/silverstripe-s3/pull/60
- https://github.com/silverstripe/silverstripe-tx-translator/pull/16
- https://github.com/silverstripe/silverstripe-upgrader/pull/206
- https://github.com/silverstripe/sspak/pull/96
- https://github.com/silverstripe/silverstripe-raygun/pull/73

The following don't have creative-commoners forks, though don't really seem appropriate to even have LICENSE files in them
- gatsby-poc
- nextjs-poc
- nextjs-poc-backend
- one-ring-rentals
- platform-status-page
- silverstripe-nextjs-starter
- silverstripe-elemental-layoutblock
- silverstripe-ux

**Comment by emteknetnz** [comment]
For INITIAL PEER REVIEW - this is my proposed approach - please let me know if you agree / disagree / would change bits

## Methods of updating files in repos

1. Update .github templates so that NEW modules get a default set of meta files
2. Update EXISTING modules so that they're consistent using a script to update all the modules - repurpose this thing - https://github.com/emteknetnz/module-standardiser/blob/main/run.php that was used to do things like bulk update the supported module badges in all the README.md's

Because we need to do 2. to meet the AC's of this card, I think it makes sense to expand the scope of this card a bit to do more stuff "while we're at it"

## Meta files to update in all repos

#### Do update / overwrite (these will also be added as templates in .github)
- .editorconfig - this should be the same for all repos - no big deal they include instructions for formatting JS files even if there are no JS files in the repo
- SUPPORT.md - Says "do not use github for support", and instead directs people to primarily to community slack also forums.
- CONTRIBUTING.md - Includes a link to https://docs.silverstripe.org/en/5/contributing/code/.  Also details what the process is for disclosing security things is. I do NOT think we need a separate SECURITY.md for this - symfony includes a security link it their CONTRIBUTING.md - https://github.com/symfony/symfony/blob/6.4/CONTRIBUTING.md

####  Add if they don't already exist (these will also be added as templates in .github)
- LICENSE - BUT only update if there isn't already an existing license there. We need to be careful of existing licenses because they may contain authors who we definitely must not remove e.g. https://github.com/silverstripe/silverstripe-mfa/blob/5/LICENSE.md.  There may also be some consequences to changing an existing license to a different one (I know little about this)  Note - our convention is mostly to omit the .md extension - which I think is correct we shouldn't have markdown in here anyway, is more of a txt file.  We'll need to scan somehow to see if any existing LICENSE's are non BSD-3 and if there are any deal with those on a case by case.

#### Remove if they exist
- Files for any third party services that are no longer used e.g. .codeclimate.yml, .scrutinizer.yml, etc
- changelog.md - likely to be hopelessly out of date - https://github.com/silverstripe/silverstripe-asset-admin/blob/2/changelog.md

#### Do not update
- README.md - leave these as they are since they're custom for each repo. One exception to this is silverstripe/framework which contains out of date info for support etc - remove this content
- Linting files - sass-lint.yml, .eslintignore, phpcs.xml.dist, etc - these only make sense if they are the corresponding file with appropriate extensions in the repo. While I'd like to standardise these where appropriate, it will break linting in CI in many cases and is really outside the scope of work for this card.

**Comment by GuySartorelli** [comment]
You haven't mentioned an organisation-level README in your breakdown above. Are you implying by omission that we shouldn't have one, or do you consider this a step to be done after the above, or....?

- Methods of updating files in repos - "Because we need to do 2. to meet the AC's of this card"
  - Why is that? According to [the github docs about default "health" files](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file): "Default files will be used for any repository owned by the account that does not contain its own file of that type."

[the github docs about default "health" files] mentions what specific files are supported. The following are not included in that list, but you've included above as "will also be added as templates in .github":
- .editorconfig
- LICENSE (_explicitly_ excluded in the linked documentation)

Did you mean something else by "template"? If so, please define that or point to the relevant documentation that defines it.
And if you did mean something else - is there a compelling reason to not use the "health" file functionality for the files it _does_ support?
If you did mean something else by "template".... it's probably starting to build some scope creep. There's nothing in the acceptance criteria about files which _aren't_ supported as "health" files except validating licenses.

**Comment by emteknetnz** [comment]
That's really cool about the default health files I didn't realise that was a thing (didn't realise you had it linked in the description). That's a nice mechanism

Given that SECURITY.md is an official health file perhaps it does make sense to put the link to security@silverstripe.org in there with instructions

By "template" my (bad) assumption was that you could define "template" for these files .github that get _copied_ to new repos, rather than added in if there isn't an existing file. So given that, "templates" aren't a thing

We **will** need to scan all the modules for non BSD-3 licenses and it seems like the [existing tool](SECURITY.md) I linked to before would be useful for this. Given that tool was designed specifically to standardise specific files (including deleting files), the amount of scope creep added here is actually pretty low so I think it's worthwhile doing e.g. ensuring .editorconfig is standardised, deleting changelog.md, etc

**Comment by GuySartorelli** [comment]
Fair. Yup, sounds like that's a good plan of attack, then.

**Comment by emteknetnz** [comment]
I used github advanced search to look at all the repos with existing licences:

0bsd - 4 results
https://github.com/search?q=user%3Asilverstripe+license%3A0bsd&type=Repositories&ref=advsearch&l=&l=
- gatsby-source-silverstripe
- gatsby-starter-silverstripe
- nextjs-builder
- nextjs-toolkit

bsd-2-clause - 2 results
https://github.com/search?q=user%3Asilverstripe+license%3Absd-2-clause&type=Repositories&ref=advsearch&l=&l=
- blog
- graphql-devtools

bsd-3-clause - 134 results
https://github.com/search?q=user%3Asilverstripe+license%3Absd-3-clause&type=Repositories&ref=advsearch&l=&l=
- lots!

mit - 2 results
https://github.com/search?q=user%3Asilverstripe+license%3Amit&type=Repositories&ref=advsearch&l=&l=
- multi-domain
- gridfieldqueuedexport

No other licence types found

**Comment by emteknetnz** [comment]
I ran a quick and dirty script to find out what repos on silverstripe account (including unsupported) have no license

```
    [0] => silverstripe/.github
    [1] => silverstripe/api.silverstripe.org
    [2] => silverstripe/comment-notifications
    [3] => silverstripe/cow
    [4] => silverstripe/cwp-theme-default
    [5] => silverstripe/demo.silverstripe.org
    [6] => silverstripe/doc.silverstripe.org
    [7] => silverstripe/doorman
    [8] => silverstripe/fluent-regional
    [9] => silverstripe/forum.silverstripe.org
    [10] => silverstripe/gatsby-poc
    [11] => silverstripe/gha-auto-tag
    [12] => silverstripe/gha-ci
    [13] => silverstripe/gha-dispatch-ci
    [14] => silverstripe/gha-generate-matrix
    [15] => silverstripe/gha-issue
    [16] => silverstripe/gha-keepalive
    [17] => silverstripe/gha-pull-request
    [18] => silverstripe/gha-run-tests
    [19] => silverstripe/gha-tag-release
    [20] => silverstripe/gha-update-js
    [21] => silverstripe/github-actions-ci-cd
    [22] => silverstripe/github-issue-search-client
    [23] => silverstripe/MinkFacebookWebDriver
    [24] => silverstripe/nextjs-poc
    [25] => silverstripe/nextjs-poc-backend
    [26] => silverstripe/nutshell-api-php
    [27] => silverstripe/one-ring-rentals
    [28] => silverstripe/platform-blank
    [29] => silverstripe/platform-project
    [30] => silverstripe/platform-status-page
    [31] => silverstripe/silverstripe-activedirectory
    [32] => silverstripe/silverstripe-advancedworkflow
    [33] => silverstripe/silverstripe-akismet
    [34] => silverstripe/silverstripe-blog
    [35] => silverstripe/silverstripe-checkboxgroupfield
    [36] => silverstripe/silverstripe-comments
    [37] => silverstripe/silverstripe-config
    [38] => silverstripe/silverstripe-content-notifier
    [39] => silverstripe/silverstripe-content-widget
    [40] => silverstripe/silverstripe-contentreview
    [41] => silverstripe/silverstripe-crazy-egg
    [42] => silverstripe/.github
    [43] => silverstripe/api.silverstripe.org
    [44] => silverstripe/comment-notifications
    [45] => silverstripe/cow
    [46] => silverstripe/cwp-theme-default
    [47] => silverstripe/demo.silverstripe.org
    [48] => silverstripe/doc.silverstripe.org
    [49] => silverstripe/doorman
    [50] => silverstripe/fluent-regional
    [51] => silverstripe/forum.silverstripe.org
    [52] => silverstripe/gatsby-poc
    [53] => silverstripe/gha-auto-tag
    [54] => silverstripe/gha-ci
    [55] => silverstripe/gha-dispatch-ci
    [56] => silverstripe/gha-generate-matrix
    [57] => silverstripe/gha-issue
    [58] => silverstripe/gha-keepalive
    [59] => silverstripe/gha-pull-request
    [60] => silverstripe/gha-run-tests
    [61] => silverstripe/gha-tag-release
    [62] => silverstripe/gha-update-js
    [63] => silverstripe/github-actions-ci-cd
    [64] => silverstripe/github-issue-search-client
    [65] => silverstripe/MinkFacebookWebDriver
    [66] => silverstripe/nextjs-poc
    [67] => silverstripe/nextjs-poc-backend
    [68] => silverstripe/nutshell-api-php
    [69] => silverstripe/one-ring-rentals
    [70] => silverstripe/platform-blank
    [71] => silverstripe/platform-project
    [72] => silverstripe/platform-status-page
    [73] => silverstripe/silverstripe-activedirectory
    [74] => silverstripe/silverstripe-advancedworkflow
    [75] => silverstripe/silverstripe-akismet
    [76] => silverstripe/silverstripe-blog
    [77] => silverstripe/silverstripe-checkboxgroupfield
    [78] => silverstripe/silverstripe-comments
    [79] => silverstripe/silverstripe-config
    [80] => silverstripe/silverstripe-content-notifier
    [81] => silverstripe/silverstripe-content-widget
    [82] => silverstripe/silverstripe-contentreview
    [83] => silverstripe/silverstripe-crazy-egg
```

Let me know if there are any where we do NOT wan BSD-3 added to it

**Comment by maxime-rainville** [comment]
At first glance, I'm fine with BSD-3 on everything.

If the repo is a fork from something else, maybe validate what the original license was. The worst case scenario is if we forked something that was under something like GNU GPLv3 license, because we would be violating that license by republishing the thing under BSD-3.

If we are confident that a module was created by an employee of Silverstripe Ltd on Silverstripe Ltd time, I don't necessarily have beef with removing the name of the original author because Silverstripe would own the copyright anyway.

Also, I think it's legally allowed to publish a module under multiple licenses. For example, you could publish something under GPLv3 and if someone wants to be able to make changes without having to share them back, they can ask you for a commercial license (MySQL made a boat load of money that way back in the day). So changing the license after the fact, should be kosher in most cases as long as we own the original right on the thing.

**Comment by emteknetnz** [comment]
TODO: still need to remove existing default health files from repos

**Comment by GuySartorelli** [comment]
> The following don't have creative-commoners forks, though don't really seem appropriate to even have LICENSE files in them

You can just create a fork - forks are free. What about them makes them seem like having a license isn't appropriate? I don't feel strongly either way, so feel free to just leave your opinion and not add licenses if that's what you choose. It just feels a little arbitrary right now given some of the repos (some very long abandoned) that did get licenses added.

**Comment by GuySartorelli** [comment]
PRs merged. Reassigning to @emteknetnz for next steps (and to respond to the above comment)

**Comment by emteknetnz** [comment]
Looks like we totally misunderstood what the [health files](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) actually do

This do not "pass through" to individual repos - instead what they do is show up as links when you open a new issue or pull request, e.g. 

![image.png](https://images.zenhubusercontent.com/5dcb6f9e3c55460001028c42/1ce6111e-63be-4d15-93c5-4f17a7b0b5fa)

**Comment by emteknetnz** [comment]
I've spun off the 'update all the files' into a new issue - https://github.com/silverstripe/.github/issues/70 as it's greatly increased the scope of the original intention of this issue

I'll close this issue
