### ISSUE TITLE
Post-launch tasks for CMS 5.0.0 

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#44]
There are likely several tidy-up tasks we need to take care of once Silverstripe CMS 5.0.0 is live.

## TODO
- [ ] Update documentation on silverstripe cloud
  - There are links from the cloud docs to dev docs - but the links are hardcoded for CMS 4 docs - the version number should be ommitted from these links.
  - There are some places that specifically talk about topics in a CMS 4 centric way (e.g. [the GraphQL on cloud docs](https://servicedesk.silverstripe.cloud/support/solutions/articles/75000063363-graphql) talk about v3 and v4)
- [ ] https://github.com/silverstripe/recipe-kitchen-sink/issues/29
- [x] https://github.com/silverstripe/.github/issues/41
- [x] https://github.com/silverstripe/.github/issues/45
- [ ] https://github.com/silverstripe/.github/issues/25
- [x] [Call out composer 2 as a requirement in the doc and changelog.](https://github.com/silverstripe/developer-docs/issues/274)

## Note
- We don't have access to change the service desk dock. So we'll have to ask them to do it.
